### ISSUE TITLE
Qemacs launches dired mode by default, not scratch buffer

### ISSUE THREAD

**Issue by posguy99** [qemacs/qemacs#5]
Qemacs 5.3.3d opens to dired mode when launched with no filename.

The **scratch** buffer is there and should be opened by default when no file to open is passed.

**Comment by posguy99** [comment]
And now I see why, the whole "invoked as ffplay" is ifdef'd out beginning on line 9151 of qe.c.

This does not match the extant documentation.

**Comment by qemacs** [comment]
Indeed the ffplay hack is not relevant anymore since FFMPEG support is currently disabled.
I removed it from the documentation.

The is_player behavior is the default now, but can be disabled by setting the global variable
`is_player` to `0` in the `~/.qe/config` file using

is_player=0;

Cheers

Chqrlie.

**Comment by qemacs** [comment]
Issue closed as a feature, can be disabled with is_player=0;
