### ISSUE TITLE
toggle_line_numbers() does not actually toggle

### ISSUE THREAD

**Issue by posguy99** [qemacs/qemacs#8]
ref https://lists.nongnu.org/archive/html/qemacs-devel/2022-09/msg00006.html

The keybinding `C-c l` works to toggle line numbers on or off.  But including `toggle_line_numbers()` in ~/.qe.config does not default them to be on.

Also, `toggle_line_numbers()` appears in the list of functions displayed by `M-x TAB`, but selecting it there likewise does not toggle the line number state.

Qemacs 5.3.4k

**Comment by posguy99** [comment]
Looking forward to that commit. :)

**Comment by qemacs** [comment]
How do you expect this to work? Do you have a reference in mind? Neither emacs nor mg have a similar feature.

**Comment by posguy99** [comment]
Emacs (big emacs) can number lines, I have it configured to run with line numbers on by default.  It numbers dired windows by default as well, although I'm sure there's a knob somewhere to turn it off.  There are knobs for everything else.

I agree that none of the mg's can do it.

**Comment by qemacs** [comment]
QEmacs version 5.3.4n fixes this issue:

I changed the settings controlling the display of line and column numbers
to mimic the behavior of emacs `linum-mode`:

Instead of a window based state, there are now 3 global states and a buffer state:

- `line-number-mode`: (global) control the display of line number in mode lines
- `column-number-mode`: (global) control the display of column number in mode lines
- `global-linum-mode`: (global) control the display of line numbers in the gutter
    space for all regular buffers.
- `linum-mode`: (buffer) control the display of line numbers in the gutter space for
    this buffer (overrides `global-linum-mode` when set).

There are new commands with the same names to toggle or set these states:
- invoked without a prefix argument: toggle the current state
- invoked with a prefix argument: enable the state if argval > 0 otherwise disable it

To turn on line number display in regular buffers, just add this line in your **~/.qe/config** file:

    global-linum-mode(1);

And remove obsolete commands `toggle-line-numbers()` from this file and any **.qerc** files.

**Comment by chqrlie** [comment]
Well not really :)
Any messages output by commands while parsing and evaluating configuration files was considered an error…
I changed this and while messages still go to the *messages* buffer, only errors now go to *errors*, which gets displayed in a popup at startup time.

Chqrlie.
